name: Movie Backend

on:
    workflow_dispatch:

env:
    ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
    IMAGE_BACKEND: backend
    IMAGE_FRONTEND: frontend

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Azure login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: ACR Login
              run: |
                echo ${{ secrets.ACR_PASSWORD }} | docker login $ACR_LOGIN_SERVER -u ${{ secrets.ACR_USERNAME }} --password-stdin

            - name: Build and push backend
              run: |
                docker build -t $ACR_LOGIN_SERVER/backend:${{ github.sha }} ./backend/movie-reservation-system
                docker push $ACR_LOGIN_SERVER/backend:${{ github.sha }}

            - name: Build and push frontend
              run: |
                docker build -t $ACR_LOGIN_SERVER/frontend:${{ github.sha }} ./frontend/movie-reservation-system
                docker push $ACR_LOGIN_SERVER/frontend:${{ github.sha }}
            
            - name: Deploy Backend
              uses: azure/container-apps-deploy-action@v1
              with:
                containerAppName: movie-backend-api
                resourceGroup: rg-movie-reservation
                imageToDeploy: $ACR_LOGIN_SERVER/backend:${{ github.sha }}

            - name: Deploy Frontend
              uses: azure/container-apps-deploy-action@v1
              with:
                containerAppName: frontend
                resourceGroup: rg-movie-reservation
                imageToDeploy: $ACR_LOGIN_SERVER/frontend:${{ github.sha }}

            
